from .chamfer_distance_loss import ProbabilisticChamferDistanceLoss
from .surface_distance_loss import ProbabilisticSurfaceDistanceLoss
from .triangle_collision_loss import TriangleCollisionLoss
from .edge_crossing_loss import EdgeCrossingLoss
from .overlap_loss import OverlapLoss
from .combined_loss import CombinedMeshSimplificationLoss
