from .chamfer_distance_loss import ProbabilisticChamferDistanceLoss
from .surface_distance_loss import ProbabilisticSurfaceDistanceLoss
from .triangle_collision_loss import TriangleCollisionLoss
from .edge_crossing_loss import EdgeCrossingLoss
from .overlapping_triangles_loss import OverlappingTrianglesLoss
from .combined_loss import CombinedMeshSimplificationLoss
